name: "Build and Push"
description: "Builds a docker image with pushing to ACR"

inputs:
  image:
    description: "Image name to build"
    required: true
  dockerfile_path:
    description: "dockerfile path for Service"
    required: true
  registry:
    description: "Image registry repo e.g. myacr.azureacr.io/eshop"
    required: true
  registry_login:
    description: "Username for registry to login"
    required: true
  registry_password:
    description: "Password for registry to login"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      name: Check out code
    - uses: azure/docker-login@v1
      name: Login to ACR
      with:
        login-server: ${{ inputs.registry }}
        username: ${{ inputs.registry_login }}
        password: ${{ inputs.registry_password }}
    - uses: elgohr/Publish-Docker-Github-Action@master
      name: Build & push Docker image
      with:
        name: ${{ inputs.image }}
        tags: ${{ github.head_ref }}
        registry: ${{ inputs.registry }}
        dockerfile: ${{ inputs.dockerfile_path }}/Dockerfile
        context: src/
        username: ${{ inputs.registry_login }}
        password: ${{ inputs.registry_password }}
