name: basket-api

on:
  workflow_dispatch:
  push:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
  
  pull_request:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
env:
  SERVICE: basket-api
  IMAGE: eshop/basket.api
  REGISTRY: esocregistry.azurecr.io
  DOCKERFILE_PATH: src/Services/Basket/Basket.API

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    #if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - uses: azure/docker-login@v1
        name: Login to ACR
        with:
          login-server: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: elgohr/Publish-Docker-Github-Action@3
        name: Build & push Docker image
        with:
          name: ${{ env.IMAGE }}
          tags: ${{ github.head_ref }}
          registry: ${{ env.REGISTRY }}
          dockerfile: ${{ env.DOCKERFILE_PATH }}/Dockerfile
          context: src/
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
