name: basket-api

on:
  workflow_dispatch:
  push:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
  
  pull_request:
    branches:
    - dev

    paths:
    - src/BuildingBlocks/**
    - src/Services/Basket/**
    - .github/workflows/basket-api.yml
env:
  SERVICE: basket-api
  IMAGE: eshop/basket.api
  REGISTRY: esocregistry.azurecr.io
  DOCKERFILE_PATH: src/Services/Basket/Basket.API

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    #if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-and-push
      with:
        service: ${{ env.IMAGE }}
        service_dockerfile_path: ${{ env.DOCKERFILE_PATH }}
        registry: ${{ env.REGISTRY }}
        registry_login: ${{ secrets.REGISTRY_USERNAME }}
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}