name: catalog-api

on:
  workflow_dispatch:
  push:
    branches:
    - dev
    paths:
    - src/BuildingBlocks/**
    - src/Services/Catalog/**
    - .github/workflows/catalog-api.yml
  
  pull_request:
    branches:
    - dev
    paths:
    - src/BuildingBlocks/**
    - src/Services/Catalog/**
    - .github/workflows/catalog-api.yml
    
env:
  IMAGE: eshop/catalog.api
  CHART: catalog-api
  TAG: ${{ github.ref_name }}
  NAMESPACE: eshop
  DOCKERFILE_PATH: src/Services/Catalog/Catalog.API
  CHART_ROOT: deploy/k8s/helm/catalog-api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    #if: ${{ github.event_name != 'pull_request' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push
      uses: ./.github/workflows/actions/build-and-push
      with:
        image: ${{ env.IMAGE }}
        dockerfile_path: ${{ env.DOCKERFILE_PATH }}
        registry: ${{ secrets.REGISTRY_URL }}
        registry_login: ${{ secrets.REGISTRY_USERNAME }}
        registry_password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Run Tests
      uses: ./.github/workflows/actions/run-tests
      with:
        service: ${{ env.CHART }}
        tag: ${{ env.TAG }}

  deploy-to-aks:
    environment: Develop
    runs-on: ubuntu-latest
    needs: build-and-push
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - name: helm deploy
        uses: ./.github/workflows/actions/helm-action
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          aks_name: ${{ secrets.AKS_NAME }}
          resource_group: ${{ secrets.RESOURCE_GROUP }}
          registry_url: ${{ secrets.REGISTRY_URL }}
          image: ${{ env.IMAGE }}
          tag: ${{ env.TAG }}
          chart: ${{ env.CHART }}
          chart_root: ${{ env.CHART_ROOT }}
          namespace: ${{ env.NAMESPACE }}        