name: Infra prepare

on:
  workflow_dispatch:
  push:
    branches:
    - dev
    paths:
    - infra/**
    - .github/workflows/infra-create.yml
  
  pull_request:
    branches:
    - dev
    paths:
    - infra/**
    - .github/workflows/infra-create.yml

env:
  REGISTRY_NAME: esoc-acr

jobs:
  terraform:
      runs-on: ubuntu-latest
      steps:
        # Checkout the repo
        - uses: actions/checkout@v2
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1        
        - uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        - name: run terraform
          run: |
            terraform init
            terraform validate
            terraform plan
            terraform apply -auto-approve
          working-directory: infra
          env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
